[tool.poetry]
name = "pyutil"
version = "1.0.0"
description = ""
authors = ["m1kc (Max Musatov) <m1kc@yandex.ru>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
arrow = "=0.14.0"

[tool.poetry.dev-dependencies]
django = "^2.2"
pytest = "^5.0"
pytest-django = "^3.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
